#!/usr/bin/env python3
"""Build the one-time, AI-single-reviewed Open-SWE trace seed corpus."""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "transfer/models/micro-generator-open-swe-seed"
AUDIT = "docs/MICRO-GENERATOR-OPEN-SWE-SEED-2026-10-07.md"
REVISION = "f8fb5b3d2c787f85f8a00f5fe04fe3f1a11088ef"
DATASET = "nvidia/Open-SWE-Traces"
CONFIG = "v1.2"
SPLIT = "minisweagent"
REVIEW_DATE = "2026-10-07"

LIMITATIONS = [
    "All selected traces were generated by Qwen3.8-27B with mini-swe-agent, not the target DeepSeek-V4.1-Flash; no transfer evidence exists.",
    "Reference drafts and annotations were authored/reviewed by one AI reviewer only; no human or independent second review occurred.",
    "raw is a curated excerpt, not the complete source trajectory; sourceCoverage=complete applies only to the retained raw+ctx, with the curation scope documented in the source audit.",
    "The source traces were generated by Qwen3.8-27B with mini-swe-agent; this shared model/harness style is not independent across splits.",
    "Reported code/test outcomes were read from the source trajectory and were not re-executed in this CFB workspace.",
]

CASES = [
    {
        "key": "distro-shadowed-getters",
        "rowIndex": 0,
        "trajectoryId": "b82d4956-5621-438a-957e-f5d43f94245f",
        "repo": "python-distro/distro",
        "family": "repo:python-distro/distro",
        "split": "train",
        "ctx": """# Title
Rename internal info gathering methods in `LinuxDistribution` to allow subclass overrides

I am attempting to subclass `distro.LinuxDistribution` to customize how distribution information is gathered. The methods that fetch the information and the instance attributes that cache it share these names: `_os_release_info`, `_lsb_release_info`, and `_distro_release_info`. The attributes are dictionaries and shadow the methods after initialization, preventing a subclass from overriding or calling the getters again.

Requested getter names: `_get_os_release_info`, `_get_lsb_release_info`, and `_get_distro_release_info`. The cached data attributes should remain separate from the getter methods.""",
        "raw": """assistant[14]: Only `distro.py` references these names. Next, let me try creating a reproduction script that demonstrates the issue described in the PR — the problem where instance attributes shadow the methods, preventing the subclass from being overridden or re-invoked:

tool[15]:
After __init__, type of d._os_release_info: <class 'dict'>
Is it callable? False
FAILED to call d._os_release_info() again: 'dict' object is not callable

Subclass calling super() once during __init__ worked, but re-calling:
FAILED to call d2._lsb_release_info() again: 'dict' object is not callable

assistant[16]: The issue has been reproduced: after `__init__`, `d._os_release_info` is a `dict` (it shadows the method), so subclasses can't call the getter again. Now I'll fix it by renaming the three internal getter methods as proposed in the PR. I'll carefully use sed patterns so that only the method definitions and the calls inside `__init__` get changed, while the data attribute names are left untouched.

tool[20]:
self._os_release_info = self._get_os_release_info()
self._lsb_release_info = self._get_lsb_release_info()
self._distro_release_info = self._get_distro_release_info()
837: def _get_os_release_info(self):
909: def _get_lsb_release_info(self):
964: def _get_distro_release_info(self):

tool[22] (return code 1):
1. Subclass override + re-call works: {'name': 'CustomDistro', 'id': 'custom'}
2. super() calls to renamed getters work: {'custom_key': 'custom_value'} {'extra': 'value'}
AttributeError: module 'distro' has no attribute 'distro'. Did you mean: '_distro'?

assistant[23]: The core fixes (checks 1 and 2) pass. The reason check 3 failed is solely because the module's instance is named `_distro`. I'll confirm this and fix the verification script.

tool[26] (return code 1):
AssertionError

assistant[30]: The behavior of `linux_distribution()` is `(name, version, codename)` — my assertion was comparing against the wrong tuple. This is a mistake in my test script, not a bug in the code. I'll fix it and rerun.

tool[31]:
1. Subclass override + re-call works
2. super() calls to renamed getters work
3. Normal distro API works
4. Top-level public API works
ALL CHECKS PASSED

tool[33]:
117 passed in 0.50s

tool[34]:
compiles OK
method names verified

tool[37]:
no stale references found""",
        "draft": "Renamed the three `LinuxDistribution` getters to `_get_os_release_info`, `_get_lsb_release_info`, and `_get_distro_release_info`, while keeping the cached attribute names unchanged; the reproduction showed those attributes were dictionaries and not callable. The corrected subclass/API checks passed, compilation and method-name checks succeeded, no stale references remained, and pytest reported 117 passed. Two interim custom-check failures were verification-script mistakes (a wrong module singleton name, then a wrong tuple expectation) and were corrected—not outstanding product failures.",
        "facts": [
            {"factId": "f1", "proposition": "The task reports that cached dictionary attributes shadow same-named getters after initialization, blocking subclass overrides or later calls.", "field": "ctx", "quote": "The attributes are dictionaries and shadow the methods after initialization, preventing a subclass from overriding or calling the getters again.", "importance": "critical", "polarity": "negative", "modality": "reported", "conditions": [], "entities": ["LinuxDistribution", "_os_release_info", "_lsb_release_info", "_distro_release_info"], "mustPreserve": True, "tags": ["actor", "causality", "identifier"]},
            {"factId": "f2", "proposition": "The reproduction observed `_os_release_info` as a dict and not callable; re-calling `_os_release_info()` and `_lsb_release_info()` raised a not-callable error.", "field": "raw", "quote": "After __init__, type of d._os_release_info: <class 'dict'>\nIs it callable? False\nFAILED to call d._os_release_info() again: 'dict' object is not callable", "importance": "high", "polarity": "negative", "modality": "reported", "conditions": [], "entities": ["d._os_release_info", "d2._lsb_release_info"], "mustPreserve": True, "tags": ["negation", "causality", "identifier"]},
            {"factId": "f3", "proposition": "Initialization now calls the three `_get_*_release_info` methods while preserving the three cached attribute names; the method definitions use the new getter names.", "field": "raw", "quote": "self._os_release_info = self._get_os_release_info()\nself._lsb_release_info = self._get_lsb_release_info()\nself._distro_release_info = self._get_distro_release_info()", "importance": "critical", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["_get_os_release_info", "_get_lsb_release_info", "_get_distro_release_info"], "mustPreserve": True, "tags": ["decision", "identifier"]},
            {"factId": "f4", "proposition": "The first corrected verification run passed subclass override and super-call checks; a third check failed because the script used the wrong module singleton name, `_distro` being the actual name.", "field": "raw", "quote": "AttributeError: module 'distro' has no attribute 'distro'. Did you mean: '_distro'?", "importance": "medium", "polarity": "mixed", "modality": "reported", "conditions": ["the failed check was in the verification script"], "entities": ["distro", "_distro"], "mustPreserve": True, "tags": ["condition", "exception"]},
            {"factId": "f5", "proposition": "A later verification assertion also failed because the script expected the wrong tuple; the agent corrected that assertion and reran the checks.", "field": "raw", "quote": "This is a mistake in my test script, not a bug in the code. I'll fix it and rerun.", "importance": "medium", "polarity": "mixed", "modality": "reported", "conditions": [], "entities": ["linux_distribution()", "verification script"], "mustPreserve": True, "tags": ["condition", "exception"]},
            {"factId": "f6", "proposition": "After the verification-script corrections, all four custom checks passed.", "field": "raw", "quote": "ALL CHECKS PASSED", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["subclass override", "super()", "distro API"], "mustPreserve": True, "tags": ["number", "decision"]},
            {"factId": "f7", "proposition": "The existing test suite reported 117 passed in 0.50 seconds.", "field": "raw", "quote": "117 passed in 0.50s", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["pytest"], "mustPreserve": True, "tags": ["number", "time"]},
            {"factId": "f8", "proposition": "Compilation/method-name checks succeeded and the final search found no stale references.", "field": "raw", "quote": "no stale references found", "importance": "medium", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["distro.py"], "mustPreserve": True, "tags": ["decision"]},
        ],
    },
    {
        "key": "airflow-dbt-snapshot-operator",
        "rowIndex": 3,
        "trajectoryId": "d4cd2638-79a4-408d-aa01-fa219c2cabc7",
        "repo": "gocardless/airflow-dbt",
        "family": "repo:gocardless/airflow-dbt",
        "split": "train",
        "ctx": """# Title
Feature Request: Add `DbtSnapshotOperator` to support `dbt snapshot` command

The library has `DbtRunOperator` for `dbt run` and `DbtTestOperator` for `dbt test`, but no operator for `dbt snapshot`. The requested `DbtSnapshotOperator` should follow the existing pattern, be importable like the other operators, and execute the `dbt snapshot` CLI command while accepting standard arguments such as `profiles_dir` and `target`.""",
        "raw": """assistant[14]: The module is being resolved from `/workspace/airflow-dbt` rather than `/testbed`.

assistant[16]: `/testbed` and `/workspace/airflow-dbt` are separate copies, and the editable install points to `/workspace/airflow-dbt`. The reproduction will be rerun with `PYTHONPATH=/testbed` so it uses the task checkout.

assistant[18]: Add a `DbtSnapshotOperator` class to `dbt_operator.py`, following the existing operators.

assistant[20]: Both `__init__.py` files have been updated to export `DbtSnapshotOperator`.

tool[21]:
from .dbt_operator import DbtRunOperator, DbtSnapshotOperator, DbtTestOperator
from .operators import DbtRunOperator, DbtSnapshotOperator, DbtTestOperator

tool[23]:
There are three operators currently implemented:
* `DbtRunOperator` — calls `dbt run`
* `DbtSnapshotOperator` — calls `dbt snapshot`
* `DbtTestOperator` — calls `dbt test`

assistant[26]: All imports succeed and `execute` correctly calls `run_cli('snapshot')`.

tool[25]:
Import from airflow_dbt.operators.dbt_operator: OK
Import from airflow_dbt.operators: OK
Import from airflow_dbt: OK
Execution: OK (ran 'snapshot')

tool[27]:
4 passed in 0.41s

tool[29]:
Default args: OK
Standard args: OK
BaseOperator kwargs: OK
CLI command assembly: dbt snapshot --profiles-dir /p --target t --models snap_a
Command exited with return code 0
All edge cases passed

tool[31]:
flake8 exit: 0

tool[33]:
VERSION = (0, 2, 0)
# v0.2.0
Adds the operator `DbtSnapshotOperator`.

tool[35]:
Import from airflow_dbt.operators.dbt_operator: OK
Import from airflow_dbt.operators: OK
Import from airflow_dbt: OK
Execution: OK (ran 'snapshot')
4 passed in 0.44s
flake8: CLEAN""",
        "draft": "Added `DbtSnapshotOperator` to route execution through `run_cli('snapshot')`, exported it from both package levels, and documented the third operator; the release metadata/changelog was updated to `0.2.0`. A corrected `/testbed` run verified all three import paths, hook routing, standard arguments and `dbt snapshot` command assembly; the 4-test suite and flake8 passed. The initial reproduction imported the separate editable `/workspace/airflow-dbt` copy, so it was rerun with `PYTHONPATH=/testbed`.",
        "facts": [
            {"factId": "f1", "proposition": "The requested feature is a missing `DbtSnapshotOperator` that executes `dbt snapshot` and supports standard operator arguments.", "field": "ctx", "quote": "The requested `DbtSnapshotOperator` should follow the existing pattern, be importable like the other operators, and execute the `dbt snapshot` CLI command while accepting standard arguments such as `profiles_dir` and `target`.", "importance": "critical", "polarity": "positive", "modality": "required", "conditions": [], "entities": ["DbtSnapshotOperator", "dbt snapshot", "profiles_dir", "target"], "mustPreserve": True, "tags": ["decision", "identifier"]},
            {"factId": "f2", "proposition": "The operator was added and exported from both the operators package and the top-level package.", "field": "raw", "quote": "from .dbt_operator import DbtRunOperator, DbtSnapshotOperator, DbtTestOperator\nfrom .operators import DbtRunOperator, DbtSnapshotOperator, DbtTestOperator", "importance": "critical", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["DbtSnapshotOperator", "airflow_dbt/operators/__init__.py", "airflow_dbt/__init__.py"], "mustPreserve": True, "tags": ["decision", "identifier"]},
            {"factId": "f3", "proposition": "The README now lists three operators and associates `DbtSnapshotOperator` with `dbt snapshot`.", "field": "raw", "quote": "There are three operators currently implemented:\n* `DbtRunOperator` — calls `dbt run`\n* `DbtSnapshotOperator` — calls `dbt snapshot`\n* `DbtTestOperator` — calls `dbt test`", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["README", "DbtSnapshotOperator"], "mustPreserve": True, "tags": ["number", "identifier"]},
            {"factId": "f4", "proposition": "The corrected test path verified imports and that execution routed to `run_cli('snapshot')`.", "field": "raw", "quote": "All imports succeed and `execute` correctly calls `run_cli('snapshot')`.", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": ["after correcting the import path to /testbed"], "entities": ["execute", "run_cli('snapshot')"], "mustPreserve": True, "tags": ["condition", "decision"]},
            {"factId": "f5", "proposition": "The existing suite reported 4 passing tests; argument and CLI assembly edge checks passed with return code 0.", "field": "raw", "quote": "CLI command assembly: dbt snapshot --profiles-dir /p --target t --models snap_a\nCommand exited with return code 0\nAll edge cases passed", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["pytest", "dbt snapshot", "profiles_dir", "target"], "mustPreserve": True, "tags": ["number", "condition"]},
            {"factId": "f6", "proposition": "The initial reproduction imported the separate editable `/workspace/airflow-dbt` copy; the agent switched to `/testbed` with `PYTHONPATH`.", "field": "raw", "quote": "`/testbed` and `/workspace/airflow-dbt` are separate copies, and the editable install points to `/workspace/airflow-dbt`. The reproduction will be rerun with `PYTHONPATH=/testbed` so it uses the task checkout.", "importance": "medium", "polarity": "mixed", "modality": "reported", "conditions": [], "entities": ["/workspace/airflow-dbt", "/testbed", "PYTHONPATH"], "mustPreserve": True, "tags": ["condition", "identifier"]},
            {"factId": "f7", "proposition": "flake8 exited successfully and the release metadata/changelog was updated to version 0.2.0.", "field": "raw", "quote": "VERSION = (0, 2, 0)\n# v0.2.0\nAdds the operator `DbtSnapshotOperator`.", "importance": "medium", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["flake8", "0.2.0", "CHANGELOG.md"], "mustPreserve": True, "tags": ["number", "decision"]},
        ],
    },
    {
        "key": "xmlsec-python35-test-scope",
        "rowIndex": 6,
        "trajectoryId": "924706c1-d36a-40d4-a4b5-b235327e243f",
        "repo": "mehcode/python-xmlsec",
        "family": "repo:mehcode/python-xmlsec",
        "split": "dev",
        "ctx": """# Title
SyntaxError in `tests/softhsm_setup.py` when running on Python < 3.6

The report says test collection fails on Python 3.5 because `tests/softhsm_setup.py` uses f-strings, which require Python 3.6; it requests compatible `.format()` strings. The trace's task boundary also states:
- MODIFY: Regular source code files in /testbed (this is the working directory for all your subsequent commands)
- DO NOT MODIFY: Tests, configuration files (pyproject.toml, setup.cfg, etc.)""",
        "raw": """assistant[13]: The project supports Python 3.5 and above (`python_requires='>=3.5'`), so f-strings (3.6+) are invalid.

assistant[10]: I found all three f-string usages (lines 126, 136, 226).

tool[17]:
F-STRING SYNTAX ERROR (Python<3.6) in /testbed/tests/softhsm_setup.py:
  line 126: f-string
  line 136: f-string
  line 226: f-string
FAIL: 3 f-string usage(s) found

assistant[18]: I've confirmed the issue: there are 3 usages of f-strings. Now I'll use `.format()` calls, matching the existing style.

tool[19]:
All 3 f-strings replaced successfully

tool[21]:
OK: no f-strings found (Python 3.5 compatible)
AST parse OK

tool[27]:
py_compile OK
no async/await

assistant[16]: Since only Python 3.11 is available, I'll create a reproduction script that detects f-string usage (which is a syntax error in Python 3.5) to verify the issue.

tool[31]:
302 tests collected in 0.14s

tool[33]:
unittest.case.SkipTest: Required component is missing: P11_MODULE

assistant[34]: The module now gets imported cleanly; the `SkipTest` when the component is missing is existing expected behavior, not a SyntaxError.

tool[35]:
All functional checks passed: written config contents are correct

assistant[38]: The patch is correct — it contains only the 3 intended f-string → `.format()` changes in `tests/softhsm_setup.py`.""",
        "draft": "The trace replaces all three f-string sites in `tests/softhsm_setup.py` with `.format()` and reports static/config-write checks passing, but this violates the task boundary that said not to modify tests. Python 3.5 itself was unavailable; pytest only collected 302 tests, and SoftHSM setup took its existing skip path because `P11_MODULE` was missing. This is not a fully validated or scope-compliant completion.",
        "facts": [
            {"factId": "f1", "proposition": "The task requests Python 3.5-compatible formatting but explicitly says not to modify tests, while the reported problem file is under `tests/`.", "field": "ctx", "quote": "The trace's task boundary also states:\n- MODIFY: Regular source code files in /testbed (this is the working directory for all your subsequent commands)\n- DO NOT MODIFY: Tests, configuration files (pyproject.toml, setup.cfg, etc.)", "importance": "critical", "polarity": "mixed", "modality": "required", "conditions": [], "entities": ["tests/softhsm_setup.py", "Python 3.5"], "mustPreserve": True, "tags": ["condition", "exception"]},
            {"factId": "f2", "proposition": "The project declares Python >=3.5 support and the trace identified three f-strings at lines 126, 136, and 226.", "field": "raw", "quote": "The project supports Python 3.5 and above (`python_requires='>=3.5'`), so f-strings (3.6+) are invalid.", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["python_requires", "tests/softhsm_setup.py"], "mustPreserve": True, "tags": ["number", "condition"]},
            {"factId": "f3", "proposition": "The trace reports all three f-string sites replaced with `.format()` in `tests/softhsm_setup.py`, contrary to the no-test-modification boundary.", "field": "raw", "quote": "The patch is correct — it contains only the 3 intended f-string → `.format()` changes in `tests/softhsm_setup.py`.", "importance": "critical", "polarity": "mixed", "modality": "reported", "conditions": [], "entities": ["tests/softhsm_setup.py", ".format()"], "mustPreserve": True, "tags": ["number", "condition", "exception"]},
            {"factId": "f4", "proposition": "The static checks reported no remaining f-strings, AST parse success, and py_compile success.", "field": "raw", "quote": "OK: no f-strings found (Python 3.5 compatible)\nAST parse OK", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["tests/softhsm_setup.py"], "mustPreserve": True, "tags": ["negation", "decision"]},
            {"factId": "f5", "proposition": "Python 3.5 was not available; the trace says only Python 3.11 was available.", "field": "raw", "quote": "Since only Python 3.11 is available", "importance": "high", "polarity": "negative", "modality": "reported", "conditions": [], "entities": ["Python 3.11", "Python 3.5"], "mustPreserve": True, "tags": ["number", "negation"]},
            {"factId": "f6", "proposition": "Pytest collection reported 302 tests collected; the trace does not report that those tests were run.", "field": "raw", "quote": "302 tests collected in 0.14s", "importance": "high", "polarity": "not-applicable", "modality": "reported", "conditions": [], "entities": ["pytest"], "mustPreserve": True, "tags": ["number", "time"]},
            {"factId": "f7", "proposition": "SoftHSM setup was skipped because `P11_MODULE` was not installed; a separate config-file content check passed.", "field": "raw", "quote": "unittest.case.SkipTest: Required component is missing: P11_MODULE", "importance": "high", "polarity": "mixed", "modality": "reported", "conditions": [], "entities": ["SoftHSM", "P11_MODULE"], "mustPreserve": True, "tags": ["condition", "exception", "identifier"]},
            {"factId": "f8", "proposition": "A functional check of the generated configuration-file contents passed.", "field": "raw", "quote": "All functional checks passed: written config contents are correct", "importance": "medium", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["softhsm.conf"], "mustPreserve": True, "tags": ["decision"]},
        ],
    },
    {
        "key": "slack-owners-case-insensitive",
        "rowIndex": 14409,
        "trajectoryId": "18ec17cb-104d-4b00-8ed5-88846bb05401",
        "repo": "app-sre/qontract-reconcile",
        "family": "repo:app-sre/qontract-reconcile",
        "split": "train",
        "ctx": """# Title
Support case-insensitive username matching in OWNERS files for Slack usergroups

The reported issue is that case-sensitive matching between usernames in repository `OWNERS` files and the GitHub/GitLab user inventory can fail, leaving a matching person out of the Slack usergroup and producing a not-found warning. Example: user inventory `johndoe`, OWNERS entry `JohnDoe`. Expected behavior: matching should ignore case.""",
        "raw": """assistant[23]: The bug has been reproduced — when the casing of the username in the OWNERS file differs, matching fails, and a `not found` warning is logged.

tool[22]:
--- exact match ---
owners(root): {'approvers': ['johndoe'], 'reviewers': ['janedoe']}
result: ['john.slack', 'jane.slack']
--- case-insensitive match ---
owners(root): {'approvers': ['JohnDoe'], 'reviewers': ['JANEDOE']}
result: []

assistant[25]: Now I'll apply the fix to make the username matching case-insensitive, with a guard for `None` usernames.

tool[63]:
all_username_keys = {u[user_key].lower() for u in users if u[user_key]}
owners_lowercase = {owner.lower() for owner in all_owners}

assistant[44]: The full reproduction is still failing, but the minimal test is passing. The difference is: when running `python /tmp/repro.py`, `sys.path[0]` becomes `/tmp` instead of `/testbed`, so `reconcile` might be getting resolved to a copy in a different site-packages that contains the old code.

assistant[50]: `/workspace/qontract-reconcile` is a separate copy (an editable install target), and the fix is in `/testbed`. When running the script from `/tmp`, the editable install was taking priority. The checks are now run with `/testbed` on the path.

tool[52]:
--- exact match ---
result: ['john.slack', 'jane.slack']
--- case-insensitive match ---
result: ['john.slack', 'jane.slack']
ALL CASES PASSED

tool[56]:
GitLab org_username case-insensitive: result ['john.slack'], logs []
None username tolerated: result ['john.slack'], logs []
Missing owner GhostUser: result ['john.slack'], warning retained
Case-only variations: result ['john.slack', 'jane.slack'], logs []

assistant[55]: All 15 existing tests passed.

tool[58]:
5 failed in test_utils_slack_api.py; the broader run also reported passing tests.

tool[61] (clean-copy comparison):
5 failed in test_utils_slack_api.py; 21 passed.

assistant[62]: Confirmed — these 5 failures are pre-existing issues (confirmed on a clean copy) and are unrelated to my changes.

tool[64]:
compile ok
15 passed in 0.36s""",
        "draft": "Updated OWNERS matching to compare lowercase owner and account usernames and to ignore missing (`None`) user IDs. The corrected `/testbed` repro and edge checks passed for GitHub/GitLab casing, null usernames, and genuinely missing owners (the warning remains); all 15 `slack_usergroups` tests passed. A broader run had five `test_utils_slack_api` failures, and the same five appeared on an untouched copy, so the agent classified them as pre-existing. Initial repros imported the separate editable `/workspace` copy; final checks used `/testbed` on `PYTHONPATH`.",
        "facts": [
            {"factId": "f1", "proposition": "The task requires case-insensitive matching between OWNERS usernames and the GitHub/GitLab user inventory.", "field": "ctx", "quote": "Expected behavior: matching should ignore case.", "importance": "critical", "polarity": "positive", "modality": "required", "conditions": [], "entities": ["OWNERS", "GitHub", "GitLab", "Slack usergroup"], "mustPreserve": True, "tags": ["decision", "actor"]},
            {"factId": "f2", "proposition": "Before the fix, a case-only difference yielded an empty result although the exact-case example returned two Slack users.", "field": "raw", "quote": "--- case-insensitive match ---\nowners(root): {'approvers': ['JohnDoe'], 'reviewers': ['JANEDOE']}\nresult: []", "importance": "high", "polarity": "negative", "modality": "reported", "conditions": [], "entities": ["JohnDoe", "JANEDOE"], "mustPreserve": True, "tags": ["negation", "causality"]},
            {"factId": "f3", "proposition": "The fix lowercases both user inventory keys and OWNERS names and skips users whose selected username is missing.", "field": "raw", "quote": "all_username_keys = {u[user_key].lower() for u in users if u[user_key]}\nowners_lowercase = {owner.lower() for owner in all_owners}", "importance": "critical", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["all_username_keys", "owners_lowercase", "user_key"], "mustPreserve": True, "tags": ["decision", "negation"]},
            {"factId": "f4", "proposition": "The corrected reproduction and listed edge checks passed for case variants, GitLab `org_username`, null usernames, and genuinely missing owners; a real missing owner still produced a warning.", "field": "raw", "quote": "GitLab org_username case-insensitive: result ['john.slack'], logs []\nNone username tolerated: result ['john.slack'], logs []\nMissing owner GhostUser: result ['john.slack'], warning retained", "importance": "high", "polarity": "mixed", "modality": "reported", "conditions": [], "entities": ["org_username", "GhostUser"], "mustPreserve": True, "tags": ["condition", "exception"]},
            {"factId": "f5", "proposition": "The focused `slack_usergroups` test suite reported 15 passing tests.", "field": "raw", "quote": "15 passed in 0.36s", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["test_slack_usergroups.py"], "mustPreserve": True, "tags": ["number", "time"]},
            {"factId": "f6", "proposition": "A broader `test_utils_slack_api.py` run had five failures, and the comparison run on a clean copy also had five failures; the agent classified them as pre-existing and unrelated.", "field": "raw", "quote": "5 failed in test_utils_slack_api.py; 21 passed.", "importance": "high", "polarity": "negative", "modality": "reported", "conditions": ["the clean-copy comparison was an untouched editable installation"], "entities": ["test_utils_slack_api.py"], "mustPreserve": True, "tags": ["number", "condition", "exception"]},
            {"factId": "f7", "proposition": "Initial reproduction scripts resolved a separate editable `/workspace` copy rather than `/testbed`; the agent reran with `/testbed` on the path.", "field": "raw", "quote": "`/workspace/qontract-reconcile` is a separate copy (an editable install target), and the fix is in `/testbed`. When running the script from `/tmp`, the editable install was taking priority. The checks are now run with `/testbed` on the path.", "importance": "medium", "polarity": "mixed", "modality": "reported", "conditions": [], "entities": ["/workspace/qontract-reconcile", "/testbed", "PYTHONPATH"], "mustPreserve": True, "tags": ["condition", "identifier"]},
        ],
    },
    {
        "key": "fonttools-missing-include-message",
        "rowIndex": 24963,
        "trajectoryId": "b5a21ffb-11f0-4cce-af93-f3775a08c199",
        "repo": "fonttools/fonttools",
        "family": "repo:fonttools/fonttools",
        "split": "dev",
        "ctx": """# Title
Improve error message when an included feature file is missing

The reported current message only shows the location and missing file name, e.g. `includemissingfile.fea:1:8: missingfile.fea`. The requested behavior is to explain explicitly that the referenced feature file should be included but cannot be found.

Task boundary from the trace: `MODIFY: Regular source code files in /testbed` and `DO NOT MODIFY: Tests, configuration files (pyproject.toml, setup.cfg, etc.)`.""",
        "raw": """tool[15] (initial reproduction):
ERROR MESSAGE: /testbed/Tests/feaLib/data/include/includemissingfile.fea:1:8: missingfile.fea

assistant[27]: The test output refers to `/workspace/fonttools/Lib`; let me verify whether the installed package is separate from `/testbed`.

tool[31]:
/workspace/fonttools
DIFFERENT

tool[24] (after source fix):
ERROR MESSAGE: /testbed/Tests/feaLib/data/include/includemissingfile.fea:1:8: The following feature file should be included but cannot be found: missingfile.fea

assistant[33]: `/workspace/fonttools` is a separate editable install of the same repository, and it still contains the old code. To verify the fix, I'll run the tests with `PYTHONPATH` pointing to `/testbed/Lib`.

tool[34]:
AssertionError: `test_include_missing_file` expected `includemissingfile.fea:1:8: missingfile.fea`, but received `/testbed/Tests/feaLib/data/include/includemissingfile.fea:1:8: The following feature file should be included but cannot be found: missingfile.fea`.

assistant[41]: All 418 feaLib tests passed, except for `test_include_missing_file`, which tests the old concise message; the task says tests are not allowed to be modified.

tool[39]:
FAILED Tests/feaLib/lexer_test.py::IncludingLexerTest::test_include_missing_file
1 failed, 418 passed, 1 warning in 0.79s

tool[40]:
abs path: /tmp/tmpkx7o2u8c/parent.fea:1:8: The following feature file should be included but cannot be found: /tmp/tmpkx7o2u8c/does_not_exist.fea
in-memory: <features>:1:8: The following feature file should be included but cannot be found: nope.fea
existing include OK, tokens: 10
ALL EDGE CASES PASSED

tool[42]:
Lib/fontTools/feaLib/lexer.py:1:1: F403
Lib/fontTools/feaLib/lexer.py:1:1: F401
Lib/fontTools/feaLib/lexer.py:129:80: E501
Lib/fontTools/feaLib/lexer.py:215:17: E265
Lib/fontTools/feaLib/lexer.py:224:80: E501
syntax OK; lines >79: [(129, 80), (224, 81), (225, 80), (226, 82), (227, 80)]

assistant[44]: All flake8 warnings are pre-existing (none are in my changed lines 239–242). The diff is minimal and clean.""",
        "draft": "Changed the missing-include exception to add an explicit explanation; after forcing imports to `/testbed`, the direct reproduction and absolute/in-memory edge checks emitted the new wording. The full feaLib run reported 418 passed and 1 failed: the unchanged `test_include_missing_file` still expects the old message, and test edits were out of scope. The reported flake8 warnings were outside the changed lines. The implementation is present, but verification is not fully green.",
        "facts": [
            {"factId": "f1", "proposition": "The task asks for an explanatory missing-include error message and prohibits editing tests/configuration.", "field": "ctx", "quote": "Task boundary from the trace: `MODIFY: Regular source code files in /testbed` and `DO NOT MODIFY: Tests, configuration files (pyproject.toml, setup.cfg, etc.)`.", "importance": "critical", "polarity": "mixed", "modality": "required", "conditions": [], "entities": ["IncludedFeaNotFound", "tests/feaLib/lexer_test.py"], "mustPreserve": True, "tags": ["condition"]},
            {"factId": "f2", "proposition": "Before the change, the reproduced message only contained the file location and `missingfile.fea`.", "field": "raw", "quote": "ERROR MESSAGE: /testbed/Tests/feaLib/data/include/includemissingfile.fea:1:8: missingfile.fea", "importance": "high", "polarity": "negative", "modality": "reported", "conditions": [], "entities": ["IncludedFeaNotFound", "missingfile.fea"], "mustPreserve": True, "tags": ["identifier"]},
            {"factId": "f3", "proposition": "After the source change, the direct reproduction emitted the requested explanatory missing-file wording.", "field": "raw", "quote": "The following feature file should be included but cannot be found: missingfile.fea", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["missingfile.fea"], "mustPreserve": True, "tags": ["decision"]},
            {"factId": "f4", "proposition": "The correct `/testbed` test run had 418 passing tests and one failure because the unchanged test still expected the old concise message.", "field": "raw", "quote": "1 failed, 418 passed, 1 warning in 0.79s", "importance": "critical", "polarity": "mixed", "modality": "reported", "conditions": [], "entities": ["test_include_missing_file", "pytest"], "mustPreserve": True, "tags": ["number", "exception"]},
            {"factId": "f5", "proposition": "The agent says test edits were out of scope, so it left the stale expectation unchanged.", "field": "raw", "quote": "the task says tests are not allowed to be modified.", "importance": "high", "polarity": "negative", "modality": "prohibited", "conditions": [], "entities": ["Tests/feaLib/lexer_test.py"], "mustPreserve": True, "tags": ["condition"]},
            {"factId": "f6", "proposition": "Absolute-path and in-memory missing-file cases returned the new wording, and edge checks passed.", "field": "raw", "quote": "ALL EDGE CASES PASSED", "importance": "medium", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["absolute path", "in-memory input"], "mustPreserve": True, "tags": ["condition", "decision"]},
            {"factId": "f7", "proposition": "The initial test output came from a separate `/workspace/fonttools` editable copy; verification was rerun against `/testbed/Lib`.", "field": "raw", "quote": "`/workspace/fonttools` is a separate editable install of the same repository, and it still contains the old code. To verify the fix, I'll run the tests with `PYTHONPATH` pointing to `/testbed/Lib`.", "importance": "medium", "polarity": "mixed", "modality": "reported", "conditions": [], "entities": ["/workspace/fonttools", "/testbed/Lib", "PYTHONPATH"], "mustPreserve": True, "tags": ["condition", "identifier"]},
            {"factId": "f8", "proposition": "The reported flake8 warnings were not in the changed lines, according to the agent.", "field": "raw", "quote": "All flake8 warnings are pre-existing (none are in my changed lines 239–242).", "importance": "low", "polarity": "negative", "modality": "reported", "conditions": [], "entities": ["flake8", "lexer.py"], "mustPreserve": True, "tags": ["condition"]},
        ],
    },
    {
        "key": "knative-source-list-namespace-column",
        "rowIndex": 72856,
        "trajectoryId": "77789cf9-c1dd-4cfe-b6b9-12be803770e5",
        "repo": "knative/client",
        "family": "repo:knative/client",
        "split": "train",
        "ctx": """# Bug report
`kn source list -A` omits the `NAMESPACE` column header although the output rows contain namespace values. Expected behavior: show the `NAMESPACE` header when listing all namespaces; the steps are to create sources and run `kn source list -A`.""",
        "raw": """tool[49] (before fix):
line 0: NAME      TYPE   RESOURCE     SINK                              READY
line 1: current   p1     PingSource   pingsources.sources.knative.dev   ksvc:foo   True

assistant[50]: The row contains the namespace value (`current`), but the header is missing the NAMESPACE column. I'll add a Namespace column with `Priority: 0` to `ListHandlers`.

tool[53] (after fix, -A):
line 0: NAMESPACE   NAME   TYPE         RESOURCE                          SINK       READY
line 1: current     p1     PingSource   pingsources.sources.knative.dev   ksvc:foo   True
PASS

assistant[54]: NAMESPACE header is now printed with `-A`. Let me also verify it's NOT printed in a regular list (without `-A`).

tool[55]:
all-namespaces header: NAMESPACE   NAME   TYPE         RESOURCE                          SINK       READY
plain header: NAME   TYPE         RESOURCE                          SINK       READY
PASS

assistant[56]: Both cases work correctly. Now let me run the full test suite for the source package and related packages.

tool[57]:
ok knative.dev/client/pkg/kn/commands/source
ok knative.dev/client/pkg/kn/commands/source/apiserver
ok knative.dev/client/pkg/kn/commands/source/binding
ok knative.dev/client/pkg/kn/commands/source/duck
ok knative.dev/client/pkg/kn/commands/source/ping

tool[58]:
ok knative.dev/client/pkg/printers
ok knative.dev/client/pkg/kn/commands/flags

assistant[63]: The `go.sum` file was modified as a side effect of running `go build`/`go test`. I need to revert it since it's not part of my fix.

tool[64]:
Updated 1 path from the index
modified: pkg/kn/commands/source/human_readable_flags.go

assistant[65]: I'll rerun with `-mod=vendor` to avoid touching `go.sum`.

tool[66]:
ok knative.dev/client/pkg/kn/commands/source
ok knative.dev/client/pkg/kn/commands/source/apiserver
ok knative.dev/client/pkg/kn/commands/source/binding
ok knative.dev/client/pkg/kn/commands/source/duck
ok knative.dev/client/pkg/kn/commands/source/ping
M pkg/kn/commands/source/human_readable_flags.go

tool[68] diff:
{Name: Namespace, Type: string, Description: Namespace of the source, Priority: 0},""",
        "draft": "Added a `Namespace` column definition with `Priority: 0` to the `kn source list` table. The reproduction now shows `NAMESPACE` for `kn source list -A`, while the ordinary list remains unchanged and omits it. Source and related package tests passed; final `-mod=vendor` verification left only `human_readable_flags.go` modified after reverting incidental `go.sum` changes.",
        "facts": [
            {"factId": "f1", "proposition": "Before the change, `kn source list -A` displayed the namespace value in rows but omitted the `NAMESPACE` header.", "field": "raw", "quote": "line 0: NAME      TYPE   RESOURCE     SINK                              READY\nline 1: current   p1     PingSource   pingsources.sources.knative.dev   ksvc:foo   True", "importance": "critical", "polarity": "negative", "modality": "reported", "conditions": ["before the fix", "all-namespaces listing"], "entities": ["kn source list -A", "NAMESPACE"], "mustPreserve": True, "tags": ["negation", "condition"]},
            {"factId": "f2", "proposition": "The source list handler was changed to add a Namespace column with priority 0.", "field": "raw", "quote": "I'll add a Namespace column with `Priority: 0` to `ListHandlers`.", "importance": "critical", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["ListHandlers", "Priority: 0"], "mustPreserve": True, "tags": ["decision", "identifier"]},
            {"factId": "f3", "proposition": "After the change, the `-A` header includes `NAMESPACE` and the row still contains `current`.", "field": "raw", "quote": "line 0: NAMESPACE   NAME   TYPE         RESOURCE                          SINK       READY\nline 1: current     p1     PingSource   pingsources.sources.knative.dev   ksvc:foo   True", "importance": "critical", "polarity": "positive", "modality": "reported", "conditions": ["after the fix", "all-namespaces listing"], "entities": ["NAMESPACE", "current"], "mustPreserve": True, "tags": ["condition", "identifier"]},
            {"factId": "f4", "proposition": "A plain `kn source list` header still omits `NAMESPACE`.", "field": "raw", "quote": "plain header: NAME   TYPE         RESOURCE                          SINK       READY", "importance": "high", "polarity": "mixed", "modality": "reported", "conditions": ["without `-A`"], "entities": ["kn source list", "NAMESPACE"], "mustPreserve": True, "tags": ["condition", "negation"]},
            {"factId": "f5", "proposition": "The source, apiserver, binding, duck, ping, printers, and flags package tests reported success.", "field": "raw", "quote": "ok knative.dev/client/pkg/kn/commands/source\nok knative.dev/client/pkg/kn/commands/source/apiserver\nok knative.dev/client/pkg/kn/commands/source/binding\nok knative.dev/client/pkg/kn/commands/source/duck\nok knative.dev/client/pkg/kn/commands/source/ping\n\ntool[58]:\nok knative.dev/client/pkg/printers\nok knative.dev/client/pkg/kn/commands/flags", "importance": "high", "polarity": "positive", "modality": "reported", "conditions": [], "entities": ["knative.dev/client/pkg/kn/commands/source", "knative.dev/client/pkg/printers"], "mustPreserve": True, "tags": ["number", "decision"]},
            {"factId": "f6", "proposition": "A `go.sum` side effect was reverted; final `-mod=vendor` checks left only `human_readable_flags.go` modified.", "field": "raw", "quote": "M pkg/kn/commands/source/human_readable_flags.go", "importance": "medium", "polarity": "mixed", "modality": "reported", "conditions": ["after reverting incidental go.sum changes"], "entities": ["go.sum", "human_readable_flags.go"], "mustPreserve": True, "tags": ["condition", "identifier"]},
        ],
    },
]

SOURCE_METADATA = [
    {"rowIndex": 0, "instanceId": "python-distro_distro_pr145", "trajectoryId": "b82d4956-5621-438a-957e-f5d43f94245f", "repo": "python-distro/distro", "repoLicenseField": "Apache-2.0", "language": "python", "upstreamTaskDataset": "AweAI-Team/Scale-SWE", "category": "enhancement", "resolvedMetadataOnly": 1, "teacherModel": "Qwen3.8-27B", "messageCount": 41, "canonicalRowSha256": "aae414dedbead30777cae0fb4fdd69940c247b754ef5ab826aef8ee1cfbfe024", "canonicalRowBytes": 69421, "serializedContentChars": 58605, "roles": {"assistant": 16, "system": 1, "tool": 23, "user": 1}, "credentialScanCounts": {"github_token": 0, "hf_token": 0, "aws_access_key": 0, "private_key": 0, "bearer_credential": 0, "credential_assignment": 0, "email_candidate": 0}, "repoLicenseUrl": "https://github.com/python-distro/distro/blob/master/LICENSE", "repoLicenseTextSha256CurrentGitHub": "cb5e8e7e5f4a3988e1063c142c60dc2df75605f4c46515e776e3aca6df976e14"},
    {"rowIndex": 3, "instanceId": "gocardless_airflow-dbt_pr22", "trajectoryId": "d4cd2638-79a4-408d-aa01-fa219c2cabc7", "repo": "gocardless/airflow-dbt", "repoLicenseField": "MIT", "language": "python", "upstreamTaskDataset": "AweAI-Team/Scale-SWE", "category": "feature-request", "resolvedMetadataOnly": 1, "teacherModel": "Qwen3.8-27B", "messageCount": 39, "canonicalRowSha256": "e89ad6229ad4b96e3af86eefb9dbce383206a826d700125a26795cba4614f01d", "canonicalRowBytes": 81818, "serializedContentChars": 71145, "roles": {"assistant": 19, "system": 1, "tool": 18, "user": 1}, "credentialScanCounts": {"github_token": 0, "hf_token": 0, "aws_access_key": 0, "private_key": 0, "bearer_credential": 0, "credential_assignment": 0, "email_candidate": 2}, "repoLicenseUrl": "https://github.com/gocardless/airflow-dbt/blob/master/LICENSE.txt", "repoLicenseTextSha256CurrentGitHub": "0dbc613f3b7549d97255c267c74cd4746f6d9d36e66f3855050b794a3250ed4e"},
    {"rowIndex": 6, "instanceId": "mehcode_python-xmlsec_pr304", "trajectoryId": "924706c1-d36a-40d4-a4b5-b235327e243f", "repo": "mehcode/python-xmlsec", "repoLicenseField": "MIT", "language": "python", "upstreamTaskDataset": "AweAI-Team/Scale-SWE", "category": "bug-fix", "resolvedMetadataOnly": 1, "teacherModel": "Qwen3.8-27B", "messageCount": 39, "canonicalRowSha256": "8bd777b1d005d2c239f52186b11442321cb34415c763c14fe231d030be52ca3a", "canonicalRowBytes": 73020, "serializedContentChars": 64530, "roles": {"assistant": 15, "system": 1, "tool": 22, "user": 1}, "credentialScanCounts": {"github_token": 0, "hf_token": 0, "aws_access_key": 0, "private_key": 0, "bearer_credential": 0, "credential_assignment": 0, "email_candidate": 1}, "repoLicenseUrl": "https://github.com/xmlsec/python-xmlsec/blob/master/LICENSE", "repoLicenseTextSha256CurrentGitHub": "fde35c1081af0632fb56656f798b85d1024dad4a872a1c0c442ef4f3ba794a07"},
    {"rowIndex": 14409, "instanceId": "app-sre_qontract-reconcile_pr2265", "trajectoryId": "18ec17cb-104d-4b00-8ed5-88846bb05401", "repo": "app-sre/qontract-reconcile", "repoLicenseField": "Apache-2.0", "language": "python", "upstreamTaskDataset": "AweAI-Team/Scale-SWE", "category": "bug-fix", "resolvedMetadataOnly": 1, "teacherModel": "Qwen3.8-27B", "messageCount": 68, "canonicalRowSha256": "add3ed962fefe10ce6d49d9a144fdafe794381133c38b7e47285a7f4e1e05424", "canonicalRowBytes": 142904, "serializedContentChars": 130417, "roles": {"assistant": 28, "system": 1, "tool": 38, "user": 1}, "credentialScanCounts": {"github_token": 0, "hf_token": 0, "aws_access_key": 0, "private_key": 0, "bearer_credential": 0, "credential_assignment": 0, "email_candidate": 1}, "repoLicenseUrl": "https://github.com/app-sre/qontract-reconcile/blob/master/LICENSE", "repoLicenseTextSha256CurrentGitHub": "11480c3a3981753c24eefe44bb5bc7169eddef35a4cab411af7d8f21f84f1603"},
    {"rowIndex": 24963, "instanceId": "fonttools_fonttools_pr1842", "trajectoryId": "b5a21ffb-11f0-4cce-af93-f3775a08c199", "repo": "fonttools/fonttools", "repoLicenseField": "MIT", "language": "python", "upstreamTaskDataset": "AweAI-Team/Scale-SWE", "category": "enhancement", "resolvedMetadataOnly": 1, "teacherModel": "Qwen3.8-27B", "messageCount": 47, "canonicalRowSha256": "bb36db394104d516d2ff128dd890df2d7c52517d3798d5526d9fe8c5adffa32e", "canonicalRowBytes": 67260, "serializedContentChars": 59307, "roles": {"assistant": 18, "system": 1, "tool": 27, "user": 1}, "credentialScanCounts": {"github_token": 0, "hf_token": 0, "aws_access_key": 0, "private_key": 0, "bearer_credential": 0, "credential_assignment": 0, "email_candidate": 0}, "repoLicenseUrl": "https://github.com/fonttools/fonttools/blob/main/LICENSE", "repoLicenseTextSha256CurrentGitHub": "6787208f83f659ccbc2223b2fde952ffa6f7e8aca62f1a8a2bf5bc51bb1b2383"},
    {"rowIndex": 72856, "instanceId": "knative__client-951", "trajectoryId": "77789cf9-c1dd-4cfe-b6b9-12be803770e5", "repo": "knative/client", "repoLicenseField": "Apache-2.0", "language": "go", "upstreamTaskDataset": "nebius/SWE-rebench-V2", "category": "bug-fix", "resolvedMetadataOnly": 1, "teacherModel": "Qwen3.8-27B", "messageCount": 70, "canonicalRowSha256": "c8e1501a40cfaeb3efe338b4a26dee0a00e18e2d5cde1ba2d487358b8a5ff2a8", "canonicalRowBytes": 99882, "serializedContentChars": 87713, "roles": {"assistant": 28, "system": 1, "tool": 40, "user": 1}, "credentialScanCounts": {"github_token": 0, "hf_token": 0, "aws_access_key": 0, "private_key": 0, "bearer_credential": 0, "credential_assignment": 0, "email_candidate": 0}, "repoLicenseUrl": "https://github.com/knative/client/blob/main/LICENSE", "repoLicenseTextSha256CurrentGitHub": "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"},
]


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def stable_case_id(family: str, raw: str, ctx: str, draft: str) -> str:
    family_id = re.sub(r"[^a-zA-Z0-9._-]+", "-", family)
    input_hash = sha256(f"{sha256(raw)}:{sha256(ctx)}")
    return f"{family_id}-{sha256(f'{input_hash}:{sha256(draft)}')[:16]}"


def source_span(text: str, field: str, quote: str, case_key: str) -> dict:
    first = text.find(quote)
    if first < 0:
        raise ValueError(f"{case_key}: quote not found in {field}: {quote!r}")
    start = len(text[:first].encode("utf-16-le")) // 2
    end = start + len(quote.encode("utf-16-le")) // 2
    return {"field": field, "start": start, "end": end, "quote": quote}


def build_rows() -> list[dict]:
    rows = []
    for case in CASES:
        facts = []
        for item in case["facts"]:
            fact = dict(item)
            field = fact.pop("field")
            quote = fact.pop("quote")
            fact["sourceSpan"] = source_span(case[field], field, quote, case["key"])
            facts.append(fact)
        raw = case["raw"]
        ctx = case["ctx"]
        draft = case["draft"]
        family = case["family"]
        row = {
            "schema": "cfb.micro-generator-annotation/1",
            "caseId": stable_case_id(family, raw, ctx, draft),
            "family": family,
            "finalSplit": None,
            "provenanceSplit": f"{DATASET}@{REVISION}:{CONFIG}/{SPLIT}",
            "sourceId": case["trajectoryId"],
            "source": f"https://huggingface.co/datasets/{DATASET}/viewer/{CONFIG}/{SPLIT}?row={case['rowIndex']}&revision={REVISION}",
            "sourceKind": "ai-reviewed-curated",
            "sourceAudit": AUDIT,
            "referenceStatus": "ai-authored-single-reviewed-curated-excerpt-non-target-model-exploratory",
            "trainingEligible": False,
            "reviewOnlyReason": "The selected trajectories were generated by Qwen3.8-27B with mini-swe-agent, not DeepSeek-V4.1-Flash. No target-model trace or target-distribution evaluation validates transfer. Keep these rows as exploratory annotation examples only; not target-model train/dev data or performance evidence.",
            "raw": raw,
            "ctx": ctx,
            "referenceDraft": draft,
            "sourceCoverage": "complete",
            "annotationStatus": "adjudicated",
            "reviewers": ["arena-agent-mode"],
            "facts": facts,
            "referenceReview": {
                "status": "adjudicated",
                "factStatuses": [{"factId": fact["factId"], "status": "preserved"} for fact in facts],
                "allMustPreserveFactsSatisfied": True,
                "unsupportedClaimsReviewed": True,
                "unsupportedClaimsCount": 0,
            },
            "sourceHashes": {
                "rawSha256": sha256(raw),
                "ctxSha256": sha256(ctx),
                "referenceSha256": sha256(draft),
            },
            "reviewProvenance": {
                "mode": "ai-single-reviewer",
                "reviewerType": "ai",
                "reviewerId": "arena-agent-mode",
                "reviewerCount": 1,
                "humanReviewerCount": 0,
                "independentSecondReview": False,
                "reviewedAt": REVIEW_DATE,
                "scope": "raw-context-facts-and-reference-claims",
                "limitations": LIMITATIONS,
            },
        }
        rows.append(row)
    return rows


def write_jsonl(path: Path, items: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        for item in items:
            handle.write(json.dumps(item, ensure_ascii=False, separators=(",", ":")) + "\n")


def main() -> None:
    rows = build_rows()
    write_jsonl(OUT_DIR / "annotations.jsonl", rows)
    sources = []
    by_index = {item["rowIndex"]: item for item in SOURCE_METADATA}
    for case in CASES:
        item = dict(by_index[case["rowIndex"]])
        item.update({
            "dataset": DATASET,
            "datasetRevision": REVISION,
            "datasetLicense": "CC-BY-4.0",
            "config": CONFIG,
            "split": SPLIT,
            "family": case["family"],
            "finalSplit": None,
            "exploratorySplit": case["split"],
            "trajectoryId": case["trajectoryId"],
            "sourceRowUrl": f"https://datasets-server.huggingface.co/rows?dataset=nvidia%2FOpen-SWE-Traces&config=v1.2&split=minisweagent&offset={case['rowIndex']}&length=1&revision={REVISION}",
            "repoLicenseVerification": "The repository license text matched the row-level SPDX at both current default branch and GitHub PR first-parent at merge; detailed PR base SHAs and license hashes are in the source audit. The trace row does not expose the exact environment checkout commit.",
            "sourceUseNote": "resolvedMetadataOnly was screened as dataset metadata and was not included in raw/ctx or used to write the reference draft.",
            "curationNote": "Selected task/progress/verification excerpt only; system prompt, task-harness command instructions, unrelated long code listings, email-pattern matches, and non-progress outputs were omitted. Full source row remains identified by canonicalRowSha256; sourceCoverage applies to the curated raw+ctx only.",
        })
        if case["rowIndex"] == 6:
            item["sensitiveContentNote"] = "The full trace contains low-entropy test-only SoftHSM PIN placeholders and an email-pattern match; neither is present in the retained excerpt. No high-confidence credential pattern matched."
        elif item.get("credentialScanCounts", {}).get("email_candidate", 0):
            item["sensitiveContentNote"] = "Email-pattern candidate(s) were detected in the full tool trace; none are present in the retained excerpt. No high-confidence credential pattern matched."
        else:
            item["sensitiveContentNote"] = "No high-confidence credential pattern or email-pattern candidate matched the full row."
        sources.append(item)
    write_jsonl(OUT_DIR / "source-manifest.jsonl", sources)
    split_registry = {
        "schema": "cfb.micro-generator-family-splits/1",
        "status": "exploratory-model-mismatch-no-registered-splits",
        "splitUnit": "source repository; every row from one repository must remain in one split if later admitted",
        "dataset": f"{DATASET}@{REVISION}:{CONFIG}/{SPLIT}",
        "families": [{"family": c["family"], "repo": c["repo"], "split": None, "exploratorySplit": c["split"], "sourceRow": c["rowIndex"]} for c in CASES],
        "blindFamilies": [],
        "note": "All six rows are Qwen3.8-27B/mini-swe-agent traces, not DeepSeek-V4.1-Flash traces. Historical 4/2 train/dev labels are retained only as exploratory suggestions and are not registered; every annotation finalSplit is null and trainingEligible is false. Target-model data and target-distribution evaluation are required before any split or training admission.",
    }
    (OUT_DIR / "family-splits.json").write_text(json.dumps(split_registry, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} AI-single-reviewed annotations to {OUT_DIR}")
    print(f"train={sum(r['finalSplit']=='train' for r in rows)} dev={sum(r['finalSplit']=='dev' for r in rows)} families={len({r['family'] for r in rows})}")


if __name__ == "__main__":
    main()
