
import fs from 'node:fs';
const rd = (p) => fs.readFileSync(p, 'utf8').trim().split('\n').filter(Boolean).map((l) => JSON.parse(l));
const dev = rd('.cfb-offline/sft/dev.jsonl');
const train = rd('.cfb-offline/sft/train.jsonl');
console.log('=== train.jsonl 第一行的键 ===');
console.log('  ' + Object.keys(train[0]).join(', '));
console.log('  meta 的键: ' + Object.keys(train[0].meta || {}).join(', '));
console.log('');
console.log('=== dev.jsonl 第一行的键 ===');
console.log('  ' + Object.keys(dev[0]).join(', '));
console.log('');
console.log('=== ctx 到底是不是恒定的 ===');
const ctxLens = dev.map((r) => [...String(r.ctx)].length);
const uniq = new Set(ctxLens);
console.log('  dev ctx 长度种类数: ' + uniq.size + ' / ' + dev.length + ' 条');
console.log('  取值: ' + [...uniq].slice(0, 12).join(', '));
console.log('');
console.log('=== ctx 前 400 字（第 1 条）===');
console.log(dev[0].ctx.slice(0, 400));
console.log('');
console.log('=== ctx 后 200 字（第 1 条）===');
console.log(dev[0].ctx.slice(-200));
console.log('');
console.log('=== raw 前 300 字（第 1 条）===');
console.log(dev[0].raw.slice(0, 300));
console.log('');
console.log('=== 两条不同单元的 ctx 是否相同？ ===');
console.log('  第1条 ctx 与第2条 ctx 相同? ' + (dev[0].ctx === dev[1].ctx));
console.log('  第1条 ctx 与第50条 ctx 相同? ' + (dev[0].ctx === dev[49].ctx));
const c0 = dev[0].ctx, c1 = dev[1].ctx;
let same = 0; const m = Math.min(c0.length, c1.length);
for (let i = 0; i < m; i++) if (c0[i] === c1[i]) same++;
console.log('  第1/2条 ctx 逐字符相同的前缀长度: ' + same + ' / ' + m);
