import io, json
rows = [json.loads(l) for l in io.open(r'D:\cfb\.cfb-offline\ruler\raw-mine-shortlist.jsonl', encoding='utf-8') if l.strip()]
OUT = io.open(r'D:\cfb\.cfb-offline\_ctxlook.txt','w',encoding='utf-8')
def p(s): OUT.write(s + '\n')
p('单元数 %d' % len(rows))
p('字段: %s' % sorted(rows[0].keys()))
o = rows[0]
p('')
p('=== ctx 长度分布 ===')
L = sorted(len(r.get('ctx') or '') for r in rows)
p('min %d p25 %d 中位 %d p75 %d p90 %d max %d' % (L[0], L[len(L)//4], L[len(L)//2], L[3*len(L)//4], L[int(len(L)*.9)], L[-1]))
p('')
p('=== ctx 里有没有代码/工具输出？统计 if 行号前缀 / 反引号 / 文件名 ===')
import re
n_lineno = sum(1 for r in rows if re.search(r'^\s*\d+[:|]', r.get('ctx') or '', re.M))
n_fence  = sum(1 for r in rows if '```' in (r.get('ctx') or ''))
n_tool   = sum(1 for r in rows if re.search(r'(read_file|grep|bash|edit_file|str_replace|run_command|execute)', r.get('ctx') or ''))
n_file   = sum(1 for r in rows if re.search(r'[\w./-]+\.(js|ts|py|json|ya?ml|go|rs|mjs|md)\b', r.get('ctx') or ''))
p('含「行号:」前缀的：%d/%d' % (n_lineno, len(rows)))
p('含 ``` 围栏的   ：%d/%d' % (n_fence, len(rows)))
p('含工具名的      ：%d/%d' % (n_tool, len(rows)))
p('含文件名的      ：%d/%d' % (n_file, len(rows)))
p('')
p('=== 第 0 条 ctx 前 1800 字 ===')
p((o.get('ctx') or '')[:1800])
p('')
p('=== 第 0 条 raw 前 700 字 ===')
p((o.get('raw') or '')[:700])
OUT.close(); print('ok')